### ISSUE TITLE
Benchmarks!

### ISSUE THREAD

**Issue by svenstaro** [leudz/shipyard#61] opened 2020-03-07 12:06 UTC
Everybody loves to benchmark their ECS. Could you add some benchmarks to see how this stacks up?

[0] https://github.com/lschmierer/ecs_bench
[1] https://www.reddit.com/r/rust/comments/9srhuc/pyro_a_fast_small_and_documented_entity_component/

By the way, I really dig the design behind shipyard, stellar work!

**Comment by leudz** [comment] 2020-03-08 01:21
Thank you!

Regarding benchmarks, while I get why everyone is measuring to see how well they do, I'm ok with whatever shipyard has. Not just because I made it, more because of how it works/allows and its API.
It's probably not the case for everyone though. Before showing some graphs, I just want to point out a few things:

- Benchmarks rarely reflect real performance, it's always good to mention it  
for example in a real program you'll very likely add a bunch of entities with the same components and then do the same thing with other entities  
shipyard takes advantage of these clusters when there's no pack
- In almost all scenarios, if your bottleneck is the ECS, you have to change your algorithm and not your ECS  
very simple example: O(n²) collision checks
- Especially in the current Rust community these benchmarks don't really matter because games are small (this might change in the future and I hope it does)
- To make somewhat accurate benchmarks a lot of scenarios have to be explored but it takes a lot of time and efforts

![build graph](https://raw.githubusercontent.com/leudz/ecs_bench/master/graph/build.png)
![update graph](https://raw.githubusercontent.com/leudz/ecs_bench/master/graph/update.png)

Even if very few things are measured there's still a lot to say.

You'll notice that shipyard is not doing all that well in adding new entities. It's not catastrophic but it could be a lot better.
There's two main reasons:

- Packs - these two tests are packed as much as possible, in the sequential test it doesn't cost much but in the parallel one there's two packs
- No bulk operation - this is especially important at the beginning of the loop because shipyard uses multiple `Vec` reallocating several times

Since I have optimized for iteration speed, let's look at the figures. The parallel update benchmark is a bit weird, I tried to use sequential iterator and just rely on system parallelism but it took the same time. I'm not exactly sure why but there's no work done in the systems so it's hard to compensate the cost of parallelism.

As for sequential iteration speed, it's not a bug (I checked with `black_box`), the scale is just too big. The result was `240 ns/iter (+/- 10)`, tightly packed storages have (very) fast iteration speed. Without pack it's about as fast as specs.

Finally, shipyard isn't that well optimized, some aspects are, like tightly packed storage iteration. But there are multiple cases where interesting information is discarded because it's a lot simpler to implement.

I hope this was informative, I could've made a simple answer (sorry) but this way I know there's some context if other people look into this issue. And the code is in [this repo](https://github.com/leudz/ecs_bench).

**Comment by svenstaro** [comment] 2020-03-08 02:39
Wow I certainly didn't expect such a detailed answer so quickly. I think it's fair that shipyard optimizes for iteration speed more than adding/removing since iteration is more than likely done more often.

Perhaps your insights (or a link to this issue) as should he added to the README?

Continue doing what you're doing. I really like an ECS with a focus on ergonomics.

**Comment by leudz** [comment] 2020-03-08 04:40
Iteration over add/remove speed mostly comes from packs. They had to be integrated very early since they impact everything. And by definition they give super fast iteration, I can't take credit for them though, it's all @skypjack.  
The other big thing is bulk operations but since it's basically a second way of doing already available operations, I preferred to leave them for later.
These operations are definitely planned but they probably won't be implemented before #57 and #22 since events will change a fair bit of code.

There's also another operation not present in these benchmarks: adding/removing components.
Shipyard should be pretty good at it, the change only affects the storage where you make the operation, making it very flexible for the user and allowing some multithreading where other implementations might not be able to.

Good idea 👍  I'll add a sentence or two to the readme and link here.

**Comment by skypjack** [comment] 2020-03-08 14:33
Thanks for the credits @leudz I'm glad when people don't try to make other people ideas their own. :wink: 
Btw we should put a cross reference in our README files imho. What do you think about? :heart:

**Closed** 2020-03-08 19:56 UTC
