### ISSUE TITLE
panic on try_run_workload()

### ISSUE THREAD

**Issue by hasenbanck** [leudz/shipyard#95] opened 2020-06-05 14:35 UTC
Hi,

I'm currently prototyping the layout of a project of mine and created a minimal ECS workload:

```rust
        const MAIN_WORKLOAD: &str = "MAIN_WORKLOAD";
        self.world
            .add_workload(MAIN_WORKLOAD)
            .with_system(system!(gfx_render_system))
            .build();

        if let Err(error) = self.world.try_run_workload(MAIN_WORKLOAD) {
            handle_workload_error(error)?;
        }
```

```rust
/// GFX render system
pub fn gfx_render_system(
    mut renderer: UniqueViewMut<Renderer>,
    mut status: UniqueViewMut<WindowStatus>,
) -> Result<()> {
    if status.resize_requested {
        renderer.resize(status.width, status.height);
        status.resize_requested = false;
    }

    renderer.render();
    info!("Was called");

    Ok(())
}
```

When calling ```try_run_workload(MAIN_WORKLOAD)``` the program will panic with the following error:

```shell
Jun 05 16:26:36.986  INFO quantize::ecs::system::gfx_render: Was called
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\slice\mod.rs:2842:10
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\fmt\mod.rs:1063
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:470
  10: std::panicking::begin_panic_handler
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:378
  11: core::panicking::panic_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\panicking.rs:85
  12: core::panicking::panic_bounds_check
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\panicking.rs:63
  13: core::slice::{{impl}}::index<alloc::boxed::Box<Fn<(shipyard::world::World*)>>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\slice\mod.rs:2842
  14: core::slice::{{impl}}::index<alloc::boxed::Box<Fn<(shipyard::world::World*)>>,usize>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\slice\mod.rs:2707
  15: alloc::vec::{{impl}}::index<alloc::boxed::Box<Fn<(shipyard::world::World*)>>,usize>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc\vec.rs:1890
  16: shipyard::world::World::try_run_workload_index
             at C:\Users\Nils\.cargo\registry\src\github.com-1ecc6299db9ec823\shipyard-0.4.0\src\world\mod.rs:825
  17: shipyard::world::World::try_run_workload<str*>
             at C:\Users\Nils\.cargo\registry\src\github.com-1ecc6299db9ec823\shipyard-0.4.0\src\world\mod.rs:808
...
```
It seems the system was executed once and then ran into the panic.

The odd thing: Replacing ```try_run_workload(MAIN_WORKLOAD)``` with ```try_run_default()``` works fine though. 

Is this the intended behavior? Did I miss something?

**Comment by leudz** [comment] 2020-06-05 15:10
Hi, this is definitely not the intended behavior, a `try_*` method shouldn't panic - ever.

I was able to reproduce it by adding multiple workloads with the same name. Apparently I didn't handle this case and there's no test for it.

```rust
let world = World::new();

for _ in 0..2 {
    world.add_workload("").with_system(system!(|| {})).build();
}

world.try_run_workload("").unwrap();
```

`run_default` doesn't have this issue because it'll remember the first one and ignore the second one. If you reassign the default it should give you an error too.

Thank you for finding this and sorry for the inconvenience.

**Comment by hasenbanck** [comment] 2020-06-05 15:16
@leudz Thank you very much for your fast replay. Bug happen. Happy to assist.

**Closed** 2020-06-05 17:19 UTC
Labels: bug

**Comment by leudz** [comment] 2020-06-05 19:33
Could you check if the fix makes your real code work?
I just want to make sure it's not another bug 😄

**Comment by hasenbanck** [comment] 2020-06-05 20:01
@leudz I re-tested the issue with shipyard v0.4.1. I now get the (helpful) error mesasge:

```A workload with this name already exists.```

This error is actually valid, since I added the workload in the main loop and not in the setup code, which I now fixed.

I think this is the expected behavior now and the issue seems resolved.

**Comment by leudz** [comment] 2020-06-05 20:03
Great, thanks again!
